version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    steps:
      - checkout
      - run:
          name: Collect coverage
          command: ./gradlew reportCoverage
      - run:
          name: Upload coverage reports to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2.1
  coverage:
    jobs:
      - build
